### ISSUE TITLE
Save and load nonvolatile state

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitmatter#7]
Certain attributes are marked as non-volatile. These must be written to a backing file and loaded on startup. This is how commissioning information is preserved over restarts.

The simplest thing would be to load and write a json file as-needed. This will easily work on CircuitPython too.

**Comment by tannewt** [comment]
This is done in https://github.com/adafruit/circuitmatter/commit/6b9090e2f43b0642aa6597763d3d2cf58e211f44

**Comment by Apollon77** [comment]
How did you decided if an attribute is non volatile? If you just use the spec flagging you might not have all needed ones.

Matter.js uses the best practice: When an attribute is writable OR non-volatiove then we persist it. For some writable attributes the Non-volatile flagging is missing but in fact if these are config then it only makes sense to also persist them- Spec is a bit vague here because it states that non-volatile should be persisted or "when needed" :-)

So maybe you should think to also include writable ones

**Comment by tannewt** [comment]
I was following the spec. I haven't run into the case where writable attributes are used. Thanks for the heads up! I'll file an issue.

**Comment by Apollon77** [comment]
Heh .. yes .. the spec is not clear in this point
